export const COMARCAS = [
    'Comarca de São Francisco do Pará',
    'Comarca de Ourém',
    'Comarca de Prainha',
    'Comarca de Xinguara',
    'Comarca de São Miguel do Guamá',
    'Comarca de Portel',
    'Comarca de Bonito',
    'Comarca de Anajás',
    'Comarca de São Paulo - Foro Regional V - São Miguel Paulista',
    'Comarca de Magalhães Barata',
    'Comarca de Faro',
    'Comarca de Santana do Araguaia',
    'Comarca de São Luís',
    'Comarca de Carpina',
    'Comarca de Mãe do Rio',
    'Comarca de Mojú',
    'Comarca de Benevides',
    'Comarca de Óbidos',
    'Comarca de São João de Pirabas',
    'Comarca de Icoaraci',
    'Comarca de Anapú',
    'Comarca de Santa Maria do Pará',
    'Comarca de Capitão Poço',
    'Comarca de Jacundá',
    'Comarca de Santa Izabel do Pará',
    'Comarca de Breves',
    'Comarca de Peixe-Boi',
    'Comarca de Vitória do Xingu',
    'Comarca de Primavera',
    'Comarca de Cachoeira do Arari',
    'Comarca de Bagre',
    'Ananindeua',
    'Comarca de Marituba',
    'Comarca do Recife',
    'Comarca de Muaná',
    'Comarca de Salvaterra',
    'Comarca de São João do Araguaia',
    'Comarca de Bragança',
    'Comarca de Arapongas',
    'Comarca de Breu Branco',
    'Comarca de Vigia',
    'Comarca de Eldorado dos Carajás',
    'Comarca de Belém',
    'Comarca de Bujarú',
    'Comarca de Tucuruí',
    'Comarca de Santa Cruz do Arari',
    'Comarca de Monte Dourado',
    'Comarca de Cachoeira do Piriá',
    'Comarca de Santarém',
    'Comarca de Abaetetuba',
    'Comarca de Monte Alegre',
    'Comarca de Ananindeua',
    'Marabá',
    'Comarca de Acará',
    'Subseção Judiciária de Santarém',
    'Comarca de Ponta de Pedras',
    'Comarca de Itaituba',
    'Comarca de Oeiras do Pará',
    'Comarca de Ulianópolis',
    'Comarca de São Félix do Xingu',
    'Comarca de Cametá',
    'Comarca de Sobral',
    'Comarca de Gurupá',
    'Comarca de Paragominas',
    'Comarca de Tomé- Açu',
    'Comarca de Redenção',
    'Comarca de Marabá',
    'Comarca de Goianésia do Pará',
    'Comarca de Nova Timboteua',
    'Comarca de Capanema',
    'Comarca de Mocajuba',
    'Comarca de Rio Maria',
    'Comarca de Aveiro',
    'Comarca de Augusto Corrêa',
    'Comarca de Uruará',
    'Comarca de Rondon do Pará',
    'Comarca de Oriximiná',
    'Comarca de Terra Santa',
    'Comarca de Medicilandia',
    'Comarca de Aurora do Pará',
    'Comarca de Rurópolis',
    'Comarca de Porto de Moz',
    'Comarca de Limoeiro do Ajuru',
    'Comarca de Pacajá',
    'Comarca de Canaã dos Carajás',
    'Comarca de Marapanim',
    'Comarca de Senador José Porfírio',
    'Comarca de São Domingos do Capim',
    'Comarca de São Geraldo do Araguaia',
    'Comarca de Baião',
    'Comarca de Juruti',
    'Comarca de Ourilândia do Norte',
    'Comarca de Curralinho',
    'Comarca de Santo Antônio do Tauá',
    'Subseção Judiciária de Marabá-PA',
    'Seção Judiciária do Pará',
    'Tribunal de Justiça do Pará',
    'Comarca de Curuçá',
    'Comarca de Brasil Novo',
    'Comarca de Irituia',
    'Comarca de Santarém Novo',
    'Comarca de Salinópolis',
    'Comarca de Chaves',
    'Comarca de Conceição do Araguaia',
    'Comarca de Quatipurú',
    'Comarca da Capital',
    'Subseção Judiciária de Paragominas',
    'Comarca de Guarapuava',
    'Comarca de Itupiranga',
    'Comarca de Igarapé-Açú',
    'Comarca de Santa Luzia do Pará',
    'Comarca de Igarapé-Miri',
    'Comarca de São Domingos do Araguaia',
    'Tribunal Regional do Trabalho da 8a Região',
    'Comarca de Novo Repartimento',
    'Comarca de Tailândia',
    'Comarca de Jacareacanga',
    'Comarca de Novo Progresso',
    'Comarca de Parauapebas',
    'Comarca de Inhangapi',
    'Comarca de Ipixuna do Pará',
    'Comarca de Tucumã',
    'Comarca de Barcarena',
    'Comarca de Garrafão do Norte',
    'Comarca de São Caetano de Odivelas',
    'Comarca de Concórdia do Pará',
    'Comarca de Dom Eliseu',
    'Comarca de São Sebastião da Boa Vista',
    'Comarca de Alenquer',
    'Comarca de Colares',
    'Comarca de Soure',
    'Comarca de Almeirim',
    'Comarca de Melgaço',
    'Comarca de Afuá',
    'Comarca de Curionópolis',
    'Comarca de Maracanã',
    'Comarca de Viseu',
    'Comarca de Altamira',
    'Comarca de Castanhal',
].sort();
