export const AJUIZADAS_FILTER_OPTIONS = {
    portes: ['Empresa de Pequeno Porte', 'Micro Empresa', 'Demais'],
    situacaoCadastral: ['Ativa', 'Baixada', 'Inapta', 'Nula', 'Suspensa'],
    tributos: [
        'Dívida Ativa ICMS',
        'Dívida Ativa IPVA',
        'Dívida Ativa ITCD',
        'Dívida Ativa não tributária',
        'Dívida Ativa TFRH',
        'Dívida Ativa TFRM',
    ],
    statusDebito: ['Ativo', 'Cancelado', 'Extinto', 'Suspenso'],
    situacaoProtesto: [
        'Aguardando envio',
        'Aguardando recebimento',
        'Cancelado',
        'Confirmado',
        'Devolvido',
        'Enviado',
        'Gerado',
        'Não Protestado',
        'Pago',
        'Protestado',
        'Retirado',
        'Sustado',
    ],
    prescritos: [
        'Dentro do prazo prescricional',
        'Possível Prescrição',
        'Prestes a prescrever',
    ],
};
