export const PROTESTO_FILTER_OPTIONS = {
    situacoesProtesto: [
        'Aguardando envio',
        'Aguardando recebimento',
        'Cancelado',
        'Devolvido',
        'Enviado',
        'Gerado',
        'Retirado',
        'Sustado',
    ],
    ufs: [
        'AC',
        'AL',
        'AM',
        'AP',
        'BA',
        'CE',
        'DF',
        'ES',
        'EX',
        'GO',
        'MA',
        'MG',
        'MS',
        'MT',
        'PA',
        'PB',
        'PE',
        'PI',
        'PR',
        'RJ',
        'RN',
        'RO',
        'RR',
        'RS',
        'SC',
        'SE',
        'SP',
        'TO',
    ],
    portes: ['Empresa de Pequeno Porte', 'Micro Empresa', 'Demais'],
    situacaoCadastral: ['Ativa', 'Baixada', 'Inapta', 'Nula', 'Suspensa'],
    tributos: [
        'Dívida Ativa ICMS',
        'Dívida Ativa IPVA',
        'Dívida Ativa ITCD',
        'Dívida Ativa não tributária',
        'Dívida Ativa TFRH',
        'Dívida Ativa TFRM',
    ],
    statusDebito: ['Ativo', 'Cancelado', 'Extinto', 'Suspenso'],
    prescritos: [
        'Dentro do prazo prescricional',
        'Possível Prescrição',
        'Prestes a prescrever',
    ],
    enderecosProtesto: [
        'Endereço Extenso',
        'Endereço Incompleto',
        'Endereço Insuficiente',
        'Endereço Nulo',
        'Endereço válido para Protesto',
    ],
};
